version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_STACK_VERSION}
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      -./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "${ES_PORT}:9200"
    networks:
      - elk-net

  logstash:
    image: docker.elastic.co/logstash/logstash:${ELASTIC_STACK_VERSION}
    container_name: logstash
    volumes:
      -./logstash/pipeline:/usr/share/logstash/pipeline/
    ports:
      - "${LOGSTASH_PORT}:5044"
    depends_on:
      - elasticsearch
    networks:
      - elk-net

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_STACK_VERSION}
    container_name: kibana
    volumes:
      -./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "${KIBANA_PORT}:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk-net

volumes:
  esdata:
    driver: local

networks:
  elk-net:
    driver: bridge
